import {
  AdapterType,
  ModeId,
  RiskTier,
  VoiceCommandCategory,
  VoiceCommandSlotType,
} from '../types/enums.js';
import type { VoiceCommand } from '../types/models.js';

const BUILTIN_TIMESTAMP = '2026-01-01T00:00:00.000Z';

function cmd(
  partial: Omit<
    VoiceCommand,
    'schemaVersion' | 'enabled' | 'isBuiltIn' | 'createdAt' | 'updatedAt'
  >,
): VoiceCommand {
  return {
    schemaVersion: 1,
    enabled: true,
    isBuiltIn: true,
    createdAt: BUILTIN_TIMESTAMP,
    updatedAt: BUILTIN_TIMESTAMP,
    ...partial,
  };
}

const ALL_CODING_MODES = [
  ModeId.ManualDictation,
  ModeId.Command,
  ModeId.AiAssist,
  ModeId.VibeCoding,
  ModeId.Research,
  ModeId.Browser,
  ModeId.AppTesting,
  ModeId.Review,
  ModeId.Terminal,
  ModeId.StreamControl,
];

const EDITOR_MODES = [
  ModeId.ManualDictation,
  ModeId.AiAssist,
  ModeId.VibeCoding,
  ModeId.Review,
];

/** Built-in VoiceCommand registry for deterministic path execution. */
export const BUILTIN_VOICE_COMMANDS: readonly VoiceCommand[] = [
  // --- Dictation ---
  cmd({
    id: 'editor.insertText',
    displayName: 'Insert Text',
    description: 'Insert dictated code tokens at the cursor (manual dictation path).',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['type {text}', 'insert {text}', 'say {text}'],
    slotSchema: {
      text: { type: VoiceCommandSlotType.FreeText, required: true, description: 'Normalized dictation payload' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'insertText',
    allowedModeIds: [ModeId.ManualDictation, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['type const user equals await get user open paren id close paren'],
    tags: ['dictation', 'core'],
  }),
  cmd({
    id: 'editor.insertSymbol',
    displayName: 'Insert Symbol',
    description: 'Insert a spoken symbol or operator by alias.',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['{symbol}'],
    slotSchema: {
      symbol: { type: VoiceCommandSlotType.Literal, required: true, description: 'Symbol alias e.g. fat arrow' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'insertText',
    allowedModeIds: [ModeId.ManualDictation],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['fat arrow', 'optional chain', 'open brace'],
    tags: ['dictation', 'symbol'],
  }),
  cmd({
    id: 'editor.phraseUndo',
    displayName: 'Undo Last Phrase',
    description: 'Revert the last committed voice dictation phrase group.',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['undo last phrase', 'undo phrase', 'scratch that'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'phraseUndo',
    allowedModeIds: [ModeId.ManualDictation, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['undo last phrase', 'scratch that'],
    tags: ['dictation', 'undo'],
  }),
  cmd({
    id: 'editor.replaceLastWord',
    displayName: 'Replace Last Word',
    description: 'Replace the last dictated word in the current phrase.',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['replace last word with {text}'],
    slotSchema: {
      text: { type: VoiceCommandSlotType.FreeText, required: true, description: 'Replacement text' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'replaceLastWord',
    allowedModeIds: [ModeId.ManualDictation],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['replace last word with profile'],
    tags: ['dictation', 'correction'],
  }),
  cmd({
    id: 'editor.replaceLastPhrase',
    displayName: 'Replace Last Phrase',
    description: 'Replace the entire last dictated phrase with new code.',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['replace last phrase with {text}'],
    slotSchema: {
      text: { type: VoiceCommandSlotType.FreeText, required: true, description: 'Replacement phrase (grammar applied)' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'replaceLastPhrase',
    allowedModeIds: [ModeId.ManualDictation],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['replace last phrase with const user equals null'],
    tags: ['dictation', 'correction'],
  }),
  cmd({
    id: 'editor.deleteLastWord',
    displayName: 'Delete Last Word',
    description: 'Remove the last word from the most recent dictated phrase.',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['delete last word'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'deleteLastWord',
    allowedModeIds: [ModeId.ManualDictation],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['delete last word'],
    tags: ['dictation', 'correction'],
  }),
  cmd({
    id: 'editor.repeatLastPhrase',
    displayName: 'Repeat Last Phrase',
    description: 'Insert the previous dictated phrase again at the cursor.',
    category: VoiceCommandCategory.Dictation,
    grammarPatterns: ['repeat last phrase', 'repeat last'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'repeatLastPhrase',
    allowedModeIds: [ModeId.ManualDictation, ModeId.Command],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['repeat last phrase'],
    tags: ['dictation', 'correction'],
  }),

  // --- Editor structural ---
  cmd({
    id: 'editor.save',
    displayName: 'Save File',
    description: 'Save the active editor or specified files.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['save file', 'save', 'save all'],
    slotSchema: {
      filePath: { type: VoiceCommandSlotType.FileName, required: false, description: 'Optional file to save' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'save',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['save file'],
    tags: ['editor', 'file'],
  }),
  cmd({
    id: 'editor.deleteLine',
    displayName: 'Delete Current Line',
    description: 'Delete the line under the cursor.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['delete current line', 'delete line'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'transform',
    allowedModeIds: [ModeId.ManualDictation, ModeId.Command, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['delete current line'],
    tags: ['editor', 'structural'],
  }),
  cmd({
    id: 'editor.duplicateLine',
    displayName: 'Duplicate Line',
    description: 'Duplicate the current line below.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['duplicate line', 'copy line down'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'transform',
    allowedModeIds: [ModeId.ManualDictation, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'structural'],
  }),
  cmd({
    id: 'editor.moveLineUp',
    displayName: 'Move Line Up',
    description: 'Move the current line up one position.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['move line up'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'transform',
    allowedModeIds: [ModeId.ManualDictation, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'structural'],
  }),
  cmd({
    id: 'editor.moveLineDown',
    displayName: 'Move Line Down',
    description: 'Move the current line down one position.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['move line down'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'transform',
    allowedModeIds: [ModeId.ManualDictation, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'structural'],
  }),
  cmd({
    id: 'editor.selectFunction',
    displayName: 'Select Current Function',
    description: 'Expand selection to the enclosing function scope.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['select current function', 'select function'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'select',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['select current function'],
    tags: ['editor', 'selection'],
  }),
  cmd({
    id: 'editor.selectWord',
    displayName: 'Select Word',
    description: 'Select the word at the cursor.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['select word', 'select current word'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'select',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'selection'],
  }),
  cmd({
    id: 'editor.selectLine',
    displayName: 'Select Current Line',
    description: 'Select the entire current line.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['select current line', 'select line'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'select',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'selection'],
  }),
  cmd({
    id: 'editor.navigateFile',
    displayName: 'Open File',
    description: 'Navigate to a file by name or path.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['open file {filePath}', 'go to file {filePath}'],
    slotSchema: {
      filePath: { type: VoiceCommandSlotType.FileName, required: true, description: 'Target file path or name' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'navigate',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'navigation'],
  }),
  cmd({
    id: 'editor.navigateLine',
    displayName: 'Go To Line',
    description: 'Navigate to a specific line number.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['go to line {count}', 'line {count}'],
    slotSchema: {
      count: { type: VoiceCommandSlotType.Number, required: true, description: '1-based line number' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'navigate',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'navigation'],
  }),
  cmd({
    id: 'editor.navigateSymbol',
    displayName: 'Go To Symbol',
    description: 'Navigate to a symbol in the active file or workspace.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['go to {symbolName}', 'go to function {symbolName}'],
    slotSchema: {
      symbolName: { type: VoiceCommandSlotType.SymbolName, required: true, description: 'Symbol name' },
    },
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'navigate',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'navigation'],
  }),
  cmd({
    id: 'editor.commentLine',
    displayName: 'Toggle Line Comment',
    description: 'Toggle line comment on the current line or selection.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['comment line', 'toggle comment'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'transform',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'structural'],
  }),
  cmd({
    id: 'editor.formatDocument',
    displayName: 'Format Document',
    description: 'Format the active document.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['format document', 'format file'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'runVsCodeCommand',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['editor', 'format'],
  }),
  cmd({
    id: 'editor.wrapInIf',
    displayName: 'Wrap Block In If',
    description: 'Wrap the current selection in an if statement block.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['wrap block in if statement', 'wrap in if'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'transform',
    allowedModeIds: [ModeId.ManualDictation, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['wrap block in if statement'],
    tags: ['editor', 'structural'],
  }),
  cmd({
    id: 'editor.undo',
    displayName: 'Undo',
    description: 'Undo the last editor change.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['undo'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'undo',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'undo'],
  }),
  cmd({
    id: 'editor.redo',
    displayName: 'Redo',
    description: 'Redo the last undone editor change.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['redo'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'redo',
    allowedModeIds: EDITOR_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['editor', 'undo'],
  }),
  cmd({
    id: 'editor.previewPatch',
    displayName: 'Preview Patch',
    description: 'Show a short summary of the pending AI patch without applying it.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['preview patch', 'show patch', 'what is the fix'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'previewPatch',
    allowedModeIds: [ModeId.AiAssist, ModeId.VibeCoding, ModeId.Review, ModeId.Command],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['preview patch', 'what is the fix'],
    tags: ['editor', 'ai', 'patch'],
  }),
  cmd({
    id: 'editor.applyPatch',
    displayName: 'Apply Patch',
    description: 'Apply a proposed unified or structured patch.',
    category: VoiceCommandCategory.Editor,
    grammarPatterns: ['apply the fix', 'apply the patch', 'apply patch'],
    targetAdapter: AdapterType.Vscode,
    adapterAction: 'applyPatch',
    allowedModeIds: [ModeId.AiAssist, ModeId.VibeCoding, ModeId.Review],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: true,
    tags: ['editor', 'ai', 'patch'],
  }),

  // --- Mode switches ---
  cmd({
    id: 'orchestrator.setMode',
    displayName: 'Switch Mode',
    description: 'Enter a harness operating mode.',
    category: VoiceCommandCategory.Mode,
    grammarPatterns: [
      'switch to {modeId}',
      '{modeId} mode',
      'enter {modeId}',
      'switch {modeId} mode',
    ],
    slotSchema: {
      modeId: {
        type: VoiceCommandSlotType.ModeId,
        required: true,
        enum: Object.values(ModeId),
        description: 'Target mode slug',
      },
    },
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'switch_mode',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['switch to command mode', 'AI assist mode', 'manual mode'],
    tags: ['mode', 'core'],
  }),
  cmd({
    id: 'orchestrator.whatMode',
    displayName: 'What Mode',
    description: 'Report the current active harness mode.',
    category: VoiceCommandCategory.Mode,
    grammarPatterns: ['what mode', 'current mode', 'which mode'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'getMode',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['mode', 'status'],
  }),
  cmd({
    id: 'orchestrator.resumePreviousMode',
    displayName: 'Resume Previous Mode',
    description: 'Exit emergency safe mode and restore the previous mode.',
    category: VoiceCommandCategory.Mode,
    grammarPatterns: ['resume previous mode', 'resume harness'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'resume_previous_mode',
    allowedModeIds: [ModeId.EmergencySafe],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: true,
    tags: ['mode', 'safety'],
  }),

  // --- Safety / emergency ---
  cmd({
    id: 'safe.emergencyStop',
    displayName: 'Emergency Stop',
    description: 'Immediately halt AI, TTS, pending confirmations, and enter emergency safe mode.',
    category: VoiceCommandCategory.Safety,
    grammarPatterns: [
      'emergency stop',
      'stop harness',
      'stop all',
      'stop drift',
    ],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'emergency_stop',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    examples: ['emergency stop'],
    tags: ['safety', 'core', 'global'],
  }),
  cmd({
    id: 'safe.cancelPending',
    displayName: 'Cancel Pending',
    description: 'Cancel the current pending confirmation or in-flight action.',
    category: VoiceCommandCategory.Safety,
    grammarPatterns: ['cancel', 'abort', 'never mind'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'cancel_pending',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['safety', 'confirmation'],
  }),
  cmd({
    id: 'safe.confirmExecute',
    displayName: 'Confirm Execute',
    description: 'Confirm a pending medium-risk action.',
    category: VoiceCommandCategory.Safety,
    grammarPatterns: ['confirm execute'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'confirm',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['safety', 'confirmation'],
  }),
  cmd({
    id: 'safe.confirmDestructive',
    displayName: 'Confirm Destructive',
    description: 'Confirm a pending destructive action.',
    category: VoiceCommandCategory.Safety,
    grammarPatterns: ['confirm destructive'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'confirm',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['safety', 'confirmation'],
  }),
  cmd({
    id: 'safe.confirmPublish',
    displayName: 'Confirm Publish',
    description: 'Confirm a pending publish or deploy action.',
    category: VoiceCommandCategory.Safety,
    grammarPatterns: ['confirm publish'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'confirm',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['safety', 'confirmation'],
  }),
  cmd({
    id: 'safe.confirmStreamChange',
    displayName: 'Confirm Stream Change',
    description: 'Confirm a pending OBS or stream-visible change.',
    category: VoiceCommandCategory.Safety,
    grammarPatterns: ['confirm stream change'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'confirm',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['safety', 'confirmation', 'stream'],
  }),

  // --- Focus / navigation ---
  cmd({
    id: 'focus.vscode',
    displayName: 'Focus VS Code',
    description: 'Return OS focus to VS Code.',
    category: VoiceCommandCategory.Navigation,
    grammarPatterns: ['focus vscode', 'return to vscode', 'back to editor'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'set_focus',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['focus', 'navigation'],
  }),
  cmd({
    id: 'focus.browser',
    displayName: 'Focus Browser',
    description: 'Switch focus to the stream-safe browser profile.',
    category: VoiceCommandCategory.Navigation,
    grammarPatterns: ['focus browser'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'set_focus',
    allowedModeIds: [ModeId.Browser, ModeId.Research, ModeId.AppTesting, ModeId.Command],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['focus', 'navigation'],
  }),
  cmd({
    id: 'focus.terminal',
    displayName: 'Focus Terminal',
    description: 'Switch focus to the project terminal.',
    category: VoiceCommandCategory.Navigation,
    grammarPatterns: ['focus terminal'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'set_focus',
    allowedModeIds: [ModeId.Terminal, ModeId.AppTesting, ModeId.Command],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['focus', 'navigation'],
  }),
  cmd({
    id: 'orchestrator.whereAmI',
    displayName: 'Where Am I',
    description: 'Report current focus, mode, file, and project context.',
    category: VoiceCommandCategory.Navigation,
    grammarPatterns: ['where am I', 'status'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'status',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['status'],
  }),

  // --- Orchestrator meta ---
  cmd({
    id: 'orchestrator.setPrivacy',
    displayName: 'Toggle Privacy Mode',
    description: 'Enable or disable stream privacy mode.',
    category: VoiceCommandCategory.Mode,
    grammarPatterns: ['privacy on', 'privacy off', 'enable privacy', 'disable privacy'],
    slotSchema: {
      enabled: { type: VoiceCommandSlotType.Literal, required: true, enum: ['on', 'off'], description: 'Privacy state' },
    },
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'set_privacy',
    allowedModeIds: [ModeId.Command, ModeId.StreamControl, ModeId.EmergencySafe],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['privacy', 'stream'],
  }),
  cmd({
    id: 'orchestrator.setOverlayLayout',
    displayName: 'Set Overlay Layout',
    description: 'Switch overlay between debug and minimal layouts.',
    category: VoiceCommandCategory.Mode,
    grammarPatterns: ['overlay debug', 'overlay minimal', 'show debug overlay'],
    slotSchema: {
      layout: {
        type: VoiceCommandSlotType.Literal,
        required: true,
        enum: ['full_debug', 'minimal'],
        description: 'Overlay layout mode',
      },
    },
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'set_overlay_layout',
    allowedModeIds: [ModeId.Command, ModeId.StreamControl],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['overlay'],
  }),
  cmd({
    id: 'orchestrator.repeatLast',
    displayName: 'Repeat Last Command',
    description: 'Re-execute the last successful voice command.',
    category: VoiceCommandCategory.Macro,
    grammarPatterns: ['repeat last', 'do that again'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'repeat_last',
    allowedModeIds: [ModeId.Command, ModeId.Terminal, ModeId.Browser],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['macro'],
  }),
  cmd({
    id: 'orchestrator.setVerbosity',
    displayName: 'Set Verbosity',
    description: 'Change AI/audio response verbosity level.',
    category: VoiceCommandCategory.Audio,
    grammarPatterns: ['verbosity {level}', 'be brief', 'stop talking'],
    slotSchema: {
      level: {
        type: VoiceCommandSlotType.Literal,
        required: false,
        enum: ['silent', 'beep_only', 'brief', 'normal', 'deep'],
        description: 'Response length preset',
      },
    },
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'set_verbosity',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['audio', 'verbosity'],
  }),

  // --- Audio ---
  cmd({
    id: 'audio.stopTts',
    displayName: 'Stop Talking',
    description: 'Immediately interrupt in-flight TTS output.',
    category: VoiceCommandCategory.Audio,
    grammarPatterns: ['stop talking', 'mute AI', 'quiet'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'stop_tts',
    allowedModeIds: ALL_CODING_MODES,
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['audio', 'interrupt'],
  }),
  cmd({
    id: 'audio.muteStreamNarration',
    displayName: 'Mute Stream Narration',
    description: 'Disable stream-facing TTS narration.',
    category: VoiceCommandCategory.Audio,
    grammarPatterns: ['mute stream narration'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'mute_stream_narration',
    allowedModeIds: [ModeId.StreamControl, ModeId.Command],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['audio', 'stream'],
  }),

  // --- Terminal ---
  cmd({
    id: 'terminal.runDevServer',
    displayName: 'Start Dev Server',
    description: 'Run the configured dev server command for the active project.',
    category: VoiceCommandCategory.Terminal,
    grammarPatterns: ['start dev server', 'run dev server'],
    targetAdapter: AdapterType.Terminal,
    adapterAction: 'run_command',
    allowedModeIds: [ModeId.Terminal, ModeId.AppTesting, ModeId.VibeCoding],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['terminal', 'dev-server'],
  }),
  cmd({
    id: 'terminal.runTests',
    displayName: 'Run Tests',
    description: 'Run the configured project test command.',
    category: VoiceCommandCategory.Terminal,
    grammarPatterns: ['run tests', 'run test'],
    targetAdapter: AdapterType.Terminal,
    adapterAction: 'run_command',
    allowedModeIds: [ModeId.Terminal, ModeId.AppTesting, ModeId.AiAssist, ModeId.VibeCoding],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['terminal', 'test'],
  }),
  cmd({
    id: 'terminal.runLint',
    displayName: 'Run Lint',
    description: 'Run the configured lint command.',
    category: VoiceCommandCategory.Terminal,
    grammarPatterns: ['run lint'],
    targetAdapter: AdapterType.Terminal,
    adapterAction: 'run_command',
    allowedModeIds: [ModeId.Terminal, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['terminal', 'lint'],
  }),
  cmd({
    id: 'terminal.runScript',
    displayName: 'Run Named Script',
    description: 'Run an allowlisted npm/package script by name.',
    category: VoiceCommandCategory.Terminal,
    grammarPatterns: ['run {scriptName}', 'run script {scriptName}'],
    slotSchema: {
      scriptName: { type: VoiceCommandSlotType.ScriptName, required: true, description: 'Package script name' },
    },
    targetAdapter: AdapterType.Terminal,
    adapterAction: 'run_command',
    allowedModeIds: [ModeId.Terminal, ModeId.AiAssist, ModeId.VibeCoding],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['terminal'],
  }),
  cmd({
    id: 'terminal.gitStatus',
    displayName: 'Git Status',
    description: 'Run git status in the project working directory.',
    category: VoiceCommandCategory.Terminal,
    grammarPatterns: ['git status'],
    targetAdapter: AdapterType.Terminal,
    adapterAction: 'run_command',
    allowedModeIds: [ModeId.Terminal, ModeId.AiAssist, ModeId.Review, ModeId.Command],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['terminal', 'git'],
  }),
  cmd({
    id: 'terminal.cancel',
    displayName: 'Cancel Terminal Job',
    description: 'Send interrupt to the running terminal process.',
    category: VoiceCommandCategory.Terminal,
    grammarPatterns: ['cancel terminal', 'stop terminal', 'term ctrl c'],
    targetAdapter: AdapterType.Terminal,
    adapterAction: 'kill_process',
    allowedModeIds: [ModeId.Terminal, ModeId.AppTesting],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['terminal'],
  }),

  // --- Browser ---
  cmd({
    id: 'browser.openLocalhost',
    displayName: 'Open Localhost App',
    description: 'Open the configured local app URL in the stream-safe browser.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['open localhost', 'open app'],
    targetAdapter: AdapterType.Browser,
    adapterAction: 'navigate',
    allowedModeIds: [ModeId.Browser, ModeId.AppTesting, ModeId.VibeCoding],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['browser'],
  }),
  cmd({
    id: 'browser.navigate',
    displayName: 'Navigate URL',
    description: 'Navigate the browser to a URL or path.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['go to {url}', 'navigate to {url}'],
    slotSchema: {
      url: { type: VoiceCommandSlotType.UrlHost, required: true, description: 'Target URL or path' },
    },
    targetAdapter: AdapterType.Browser,
    adapterAction: 'navigate',
    allowedModeIds: [ModeId.Browser, ModeId.Research],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['browser', 'navigation'],
  }),
  cmd({
    id: 'browser.goBack',
    displayName: 'Browser Back',
    description: 'Navigate back in browser history.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['go back'],
    targetAdapter: AdapterType.Browser,
    adapterAction: 'navigate',
    allowedModeIds: [ModeId.Browser, ModeId.Research],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['browser'],
  }),
  cmd({
    id: 'browser.click',
    displayName: 'Click Element',
    description: 'Click a labeled or selected DOM element.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['click {target}'],
    slotSchema: {
      target: { type: VoiceCommandSlotType.Literal, required: true, description: 'Element label or selector' },
    },
    targetAdapter: AdapterType.Browser,
    adapterAction: 'click',
    allowedModeIds: [ModeId.Browser, ModeId.AppTesting],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['browser', 'automation'],
  }),
  cmd({
    id: 'browser.fill',
    displayName: 'Fill Field',
    description: 'Fill a form field with a value.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['fill {target} with {value}'],
    slotSchema: {
      target: { type: VoiceCommandSlotType.Literal, required: true, description: 'Field label or selector' },
      value: { type: VoiceCommandSlotType.Text, required: true, description: 'Value to enter' },
    },
    targetAdapter: AdapterType.Browser,
    adapterAction: 'fill',
    allowedModeIds: [ModeId.Browser, ModeId.AppTesting],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['browser', 'automation'],
  }),
  cmd({
    id: 'browser.readConsole',
    displayName: 'Read Console',
    description: 'Capture recent browser console messages.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['read console', 'check console'],
    targetAdapter: AdapterType.Browser,
    adapterAction: 'get_console',
    allowedModeIds: [ModeId.Browser, ModeId.AppTesting, ModeId.Research],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['browser', 'debug'],
  }),
  cmd({
    id: 'browser.runFlow',
    displayName: 'Run App Test Flow',
    description: 'Execute a named AppTestFlow.',
    category: VoiceCommandCategory.Browser,
    grammarPatterns: ['run flow {flowId}', 'run login flow'],
    slotSchema: {
      flowId: { type: VoiceCommandSlotType.FlowName, required: true, description: 'App test flow name or ID' },
    },
    targetAdapter: AdapterType.Browser,
    adapterAction: 'run_flow_step',
    allowedModeIds: [ModeId.AppTesting],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['browser', 'app-test'],
  }),

  // --- OBS / stream ---
  cmd({
    id: 'obs.setScene',
    displayName: 'Set OBS Scene',
    description: 'Switch to an allowlisted OBS scene.',
    category: VoiceCommandCategory.Obs,
    grammarPatterns: ['scene {sceneName}', 'switch scene to {sceneName}'],
    slotSchema: {
      sceneName: { type: VoiceCommandSlotType.SceneName, required: true, description: 'OBS scene name' },
    },
    targetAdapter: AdapterType.Obs,
    adapterAction: 'set_scene',
    allowedModeIds: [ModeId.StreamControl],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: true,
    tags: ['obs', 'stream'],
  }),
  cmd({
    id: 'obs.setPrivacy',
    displayName: 'OBS Privacy',
    description: 'Toggle OBS privacy scene or source visibility.',
    category: VoiceCommandCategory.Obs,
    grammarPatterns: ['enable privacy mode', 'hide transcript on overlay'],
    targetAdapter: AdapterType.Obs,
    adapterAction: 'set_privacy',
    allowedModeIds: [ModeId.StreamControl, ModeId.Command],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: false,
    tags: ['obs', 'privacy'],
  }),
  cmd({
    id: 'obs.toggleTranscript',
    displayName: 'Toggle Transcript Visibility',
    description: 'Show or hide the transcript on the stream overlay.',
    category: VoiceCommandCategory.Obs,
    grammarPatterns: ['hide transcript', 'show transcript'],
    targetAdapter: AdapterType.Obs,
    adapterAction: 'toggle_source',
    allowedModeIds: [ModeId.StreamControl],
    defaultRiskTier: RiskTier.Medium,
    requiresConfirmation: true,
    tags: ['obs', 'overlay'],
  }),

  // --- AI triggers ---
  cmd({
    id: 'ai.triggerAssist',
    displayName: 'Ask AI',
    description: 'Explicitly invoke the AI intent layer for the current utterance.',
    category: VoiceCommandCategory.Ai,
    grammarPatterns: ['ask AI {text}', 'use AI to {text}', 'explain with AI {text}'],
    slotSchema: {
      text: { type: VoiceCommandSlotType.FreeText, required: true, description: 'AI task description' },
    },
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'create_ai_task',
    allowedModeIds: [
      ModeId.AiAssist,
      ModeId.VibeCoding,
      ModeId.Research,
      ModeId.Review,
      ModeId.AppTesting,
      ModeId.Command,
      ModeId.ManualDictation,
    ],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['ai'],
  }),
  cmd({
    id: 'ai.explainError',
    displayName: 'Explain Error',
    description: 'Ask AI to briefly explain the current diagnostic error.',
    category: VoiceCommandCategory.Ai,
    grammarPatterns: ['explain this error', 'explain error briefly', 'what is wrong'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'create_ai_task',
    allowedModeIds: [ModeId.AiAssist, ModeId.Review, ModeId.AppTesting],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['ai', 'diagnostics'],
  }),
  cmd({
    id: 'ai.stopImplementation',
    displayName: 'Stop Implementation',
    description: 'Cancel an active vibe-coding implementation chain.',
    category: VoiceCommandCategory.Ai,
    grammarPatterns: ['stop implementation', 'stop vibe', 'pause vibe'],
    targetAdapter: AdapterType.Orchestrator,
    adapterAction: 'cancel_ai_task',
    allowedModeIds: [ModeId.VibeCoding, ModeId.AiAssist],
    defaultRiskTier: RiskTier.Safe,
    requiresConfirmation: false,
    tags: ['ai', 'vibe'],
  }),
];

/** Map of built-in command ID → VoiceCommand for O(1) registry lookup. */
export const BUILTIN_VOICE_COMMAND_MAP: ReadonlyMap<string, VoiceCommand> = new Map(
  BUILTIN_VOICE_COMMANDS.map((command) => [command.id, command]),
);

/** Lookup a built-in voice command by stable slug ID. */
export function getBuiltInVoiceCommand(id: string): VoiceCommand | undefined {
  return BUILTIN_VOICE_COMMAND_MAP.get(id);
}

/** Filter built-in commands available in a given mode. */
export function getBuiltInCommandsForMode(modeId: ModeId | string): VoiceCommand[] {
  return BUILTIN_VOICE_COMMANDS.filter((command) => command.allowedModeIds.includes(modeId));
}

/** Filter built-in commands by category. */
export function getBuiltInCommandsByCategory(category: VoiceCommandCategory): VoiceCommand[] {
  return BUILTIN_VOICE_COMMANDS.filter((command) => command.category === category);
}
