export const KEYWORD_MAP: Readonly<Record<string, string>> = {
  const: 'const',
  let: 'let',
  var: 'var',
  function: 'function',
  async: 'async',
  await: 'await',
  return: 'return',
  import: 'import',
  export: 'export',
  from: 'from',
  default: 'default',
  type: 'type',
  interface: 'interface',
  class: 'class',
  if: 'if',
  else: 'else',
  try: 'try',
  catch: 'catch',
  for: 'for',
  of: 'of',
  in: 'in',
  new: 'new',
  this: 'this',
  true: 'true',
  false: 'false',
  null: 'null',
  undefined: 'undefined',
  not: '!',
};

export const LITERAL_MAP: Readonly<Record<string, string>> = {
  true: 'true',
  false: 'false',
  null: 'null',
  undefined: 'undefined',
  zero: '0',
  one: '1',
  'empty string': "''",
  'empty array': '[]',
  'empty object': '{}',
};
